// GENERATED by scripts/import-macros-data.mjs from the Macros repo (lib/data/plans.ts, snacks.ts, recipes.ts).
// Do not edit by hand: change Macros' files, or the generator, and run it again.
// 3 plans, 2 bowl builds, 5 quick snacks, 11 recipes. Macros per serving, exactly as Macros has them.

export type MealSlot = "breakfast" | "lunch" | "snack" | "dinner";
export type MealPlanId = "standard" | "paleo" | "keto";
export type BowlId = "beef-rice" | "turkey-cabbage";
export type PlanMeal = { name: string; kcal: number; protein: number; carbs: number; fat: number; time: string; desc: string; fixedPortion?: boolean };
export type MealPlan = { id: MealPlanId; name: string; badge: string; desc: string; targets: { kcal: number; protein: number; carbs: number; fat: number }; meals: Record<MealSlot, PlanMeal>; extras: PlanMeal[] };
export type BowlVariant = { short: string; name: string; desc: string; kcal: number; protein: number; carbs: number; fat: number };
export type SnackPreset = { name: string; portion: string; kcal: number; protein: number; carbs: number; fat: number };
export type Recipe = { id: string; group: string; name: string; time: string; servings: number; isMealPrep: boolean; fixedPortion?: boolean; kcal: number; protein: number; carbs: number; fat: number; ingredients: string[]; steps: string[]; notes: string };

export const MEAL_PLANS: Record<MealPlanId, MealPlan> = {
  "standard": {
    "id": "standard",
    "name": "Standard",
    "badge": "Dairy · Grain · Egg-Free",
    "desc": "High protein with rice bowls, Greek yogurt, cottage cheese — adjusted for 2026 panel",
    "targets": {
      "kcal": 2100,
      "protein": 200,
      "carbs": 150,
      "fat": 75
    },
    "meals": {
      "breakfast": {
        "name": "Post-Workout Shake",
        "kcal": 664,
        "protein": 69,
        "carbs": 59,
        "fat": 25,
        "time": "6:45 AM",
        "desc": "1 scoop vanilla whey + OptiCleanse GHI packet, peanut butter, chia, strawberries, blueberries, collagen, creatine",
        "fixedPortion": true
      },
      "lunch": {
        "name": "Beef & Rice Bowl",
        "kcal": 708,
        "protein": 53,
        "carbs": 53,
        "fat": 28,
        "time": "12:00 PM",
        "desc": "85/15 beef, jasmine rice, broccoli, spinach, mushrooms, cottage cheese"
      },
      "snack": {
        "name": "Vanilla-Almond Protein Yogurt Bowl",
        "kcal": 452,
        "protein": 49,
        "carbs": 20,
        "fat": 22,
        "time": "3:30 PM",
        "desc": "Greek yogurt, vanilla whey, almond butter, almonds, cinnamon, pinch of salt"
      },
      "dinner": {
        "name": "Beef & Rice Bowl",
        "kcal": 708,
        "protein": 53,
        "carbs": 53,
        "fat": 28,
        "time": "7:30 PM",
        "desc": "85/15 beef, jasmine rice, broccoli, spinach, mushrooms, cottage cheese"
      }
    },
    "extras": [
      {
        "name": "Whey in Water",
        "kcal": 110,
        "protein": 25,
        "carbs": 2,
        "fat": 1,
        "time": "Anytime",
        "desc": "1 scoop vanilla whey shaken in water — protein top-up",
        "fixedPortion": true
      }
    ]
  },
  "paleo": {
    "id": "paleo",
    "name": "Paleo",
    "badge": "Grain-Free · Dairy-Free",
    "desc": "Sweet potato bowls, coconut yogurt, egg white protein, avocado",
    "targets": {
      "kcal": 2100,
      "protein": 175,
      "carbs": 145,
      "fat": 85
    },
    "meals": {
      "breakfast": {
        "name": "Post-Workout Shake",
        "kcal": 464,
        "protein": 64,
        "carbs": 38,
        "fat": 7,
        "time": "6:45 AM",
        "desc": "2 scoops egg white protein, almond butter, chia, strawberries, blueberries, collagen, creatine"
      },
      "lunch": {
        "name": "Beef, Egg & Sweet Potato Bowl",
        "kcal": 660,
        "protein": 44,
        "carbs": 46,
        "fat": 30,
        "time": "12:00 PM",
        "desc": "85/15 beef, egg scrambled in, roasted sweet potato, broccoli, avocado, bone broth deglaze"
      },
      "snack": {
        "name": "Paleo Cocoa Coconut Yogurt Bowl",
        "kcal": 452,
        "protein": 33,
        "carbs": 23,
        "fat": 27,
        "time": "3:30 PM",
        "desc": "Unsweetened coconut yogurt, egg white protein, cocoa powder, almonds, sea salt"
      },
      "dinner": {
        "name": "Beef, Egg & Sweet Potato Bowl",
        "kcal": 660,
        "protein": 44,
        "carbs": 46,
        "fat": 30,
        "time": "7:30 PM",
        "desc": "85/15 beef, egg scrambled in, roasted sweet potato, broccoli, avocado, bone broth deglaze"
      }
    },
    "extras": []
  },
  "keto": {
    "id": "keto",
    "name": "Keto",
    "badge": "Low-Carb · Dairy-Free",
    "desc": "Cauliflower rice bowls, hard boiled eggs, almonds, fat-forward macros",
    "targets": {
      "kcal": 2100,
      "protein": 180,
      "carbs": 23,
      "fat": 140
    },
    "meals": {
      "breakfast": {
        "name": "Keto Morning Shake",
        "kcal": 591,
        "protein": 65,
        "carbs": 9,
        "fat": 29,
        "time": "6:45 AM",
        "desc": "2 scoops egg white protein, almond butter, chia, strawberries (½ cup), MCT oil, collagen, creatine"
      },
      "lunch": {
        "name": "Keto Beef & Cauliflower Bowl",
        "kcal": 535,
        "protein": 38,
        "carbs": 4,
        "fat": 38,
        "time": "12:00 PM",
        "desc": "85/15 beef (light drain), egg scrambled in, cauliflower rice, broccoli, ½ avocado, bone broth deglaze"
      },
      "snack": {
        "name": "Keto Snack",
        "kcal": 495,
        "protein": 25,
        "carbs": 6,
        "fat": 40,
        "time": "3:30 PM",
        "desc": "3 hard boiled eggs, ½ avocado, 1oz almonds, salt, lime juice"
      },
      "dinner": {
        "name": "Keto Beef & Cauliflower Bowl",
        "kcal": 535,
        "protein": 38,
        "carbs": 4,
        "fat": 38,
        "time": "7:30 PM",
        "desc": "85/15 beef (light drain), egg scrambled in, cauliflower rice, broccoli, ½ avocado, bone broth deglaze"
      }
    },
    "extras": []
  }
};

/** Swappable builds for the Standard plan's two bowl slots (lunch and dinner). */
export const BOWL_VARIANTS: Record<BowlId, BowlVariant> = {
  "beef-rice": {
    "short": "Beef & Rice",
    "name": "Beef & Rice Bowl",
    "desc": "85/15 beef, jasmine rice, broccoli, spinach, mushrooms, cottage cheese",
    "kcal": 708,
    "protein": 53,
    "carbs": 53,
    "fat": 28
  },
  "turkey-cabbage": {
    "short": "Turkey & Cabbage",
    "name": "Turkey & Cabbage Bowl",
    "desc": "93/7 turkey, red cabbage, onion, mushrooms, cottage cheese — rice-free",
    "kcal": 470,
    "protein": 49,
    "carbs": 18,
    "fat": 21
  }
};

export const SNACK_PRESETS: SnackPreset[] = [
  {
    "name": "Beef Stick",
    "portion": "1 stick",
    "kcal": 100,
    "protein": 9,
    "carbs": 0,
    "fat": 7
  },
  {
    "name": "Coffee Black",
    "portion": "1 cup",
    "kcal": 5,
    "protein": 0,
    "carbs": 0,
    "fat": 0
  },
  {
    "name": "Coffee w/ Creamer",
    "portion": "1 cup",
    "kcal": 40,
    "protein": 1,
    "carbs": 3,
    "fat": 3
  },
  {
    "name": "Spindrift",
    "portion": "1 can",
    "kcal": 10,
    "protein": 0,
    "carbs": 2,
    "fat": 0
  },
  {
    "name": "Whey in Water",
    "portion": "1 serving",
    "kcal": 110,
    "protein": 25,
    "carbs": 2,
    "fat": 1
  }
];

export const RECIPES: Recipe[] = [
  {
    "id": "std-shake",
    "group": "standard",
    "name": "Post-Workout Shake",
    "time": "6:45 AM",
    "servings": 1,
    "isMealPrep": false,
    "fixedPortion": true,
    "kcal": 664,
    "protein": 69,
    "carbs": 59,
    "fat": 25,
    "ingredients": [
      "1 scoop vanilla whey protein powder",
      "1 packet OptiCleanse GHI Creamy Chocolate SSF",
      "1 tbsp peanut butter",
      "1 tbsp chia seeds",
      "1 cup strawberries (fresh or frozen)",
      "1 cup blueberries (fresh or frozen)",
      "1 serving collagen peptides",
      "1 serving creatine monohydrate",
      "8–10 oz water or unsweetened almond milk",
      "Ice"
    ],
    "steps": [
      "Add liquid to the blender first.",
      "Add strawberries and blueberries.",
      "Add whey, OptiCleanse GHI packet, collagen, chia, and peanut butter.",
      "Add creatine and a handful of ice if using.",
      "Blend on high 45–60 seconds until completely smooth. Drink within 30 min of training."
    ],
    "notes": "1 scoop whey isolate + 1 packet OptiCleanse GHI SSF (210 kcal · P26 · C13 · F8 per label) folds the GHI serving from the stack into the morning shake. Fixed-portion recipe: quantities stay at whole scoops/packets and never rescale with the daily target. Whey assumed as isolate (~110 kcal, 25g protein per scoop); peanut butter and chia at 1 tbsp each."
  },
  {
    "id": "std-beef-rice-bowl",
    "group": "standard",
    "name": "Beef & Rice Bowl",
    "time": "12:00 PM & 7:30 PM",
    "servings": 6,
    "isMealPrep": true,
    "kcal": 708,
    "protein": 53,
    "carbs": 53,
    "fat": 28,
    "ingredients": [
      "3 lb organic ground beef (85/15)",
      "2.5 cups dry jasmine rice",
      "2.5 cups frozen broccoli florets",
      "15 oz fresh baby spinach (three 5 oz clamshells — wilts down to ~1.5 cups cooked, ¼ cup per bowl)",
      "1 lb cremini mushrooms, sliced (two 8 oz packages — yields ~3 cups sautéed)",
      "1.5 cups cottage cheese (¼ cup per bowl)",
      "1.5 tbsp olive oil (for beef)",
      "2 tsp olive oil (for spinach + mushroom sauté)",
      "1.5 tbsp garlic powder",
      "1¼ tsp onion powder",
      "1¼ tsp smoked paprika",
      "1¼ tsp cumin",
      "1¼ tsp salt",
      "¾ tsp black pepper",
      "2.5 tbsp coconut aminos (wheat-free brand)"
    ],
    "steps": [
      "Rinse rice until water runs clear. Cook in rice cooker with water (1:1.5 rice-to-water ratio).",
      "Rinse baby spinach in a colander and let drain (it carries enough water for wilting; no need to dry).",
      "Heat 1.5 tbsp olive oil in a large skillet over medium-high. Brown the beef, breaking apart with a wooden spoon, 9–10 min until no pink remains.",
      "Drain rendered fat aggressively — tilt the pan and spoon out. For 85/15, follow with a hot-water rinse in a colander, then return to pan.",
      "Reduce heat. Add garlic powder, onion powder, paprika, cumin, salt, pepper. Stir well. Add coconut aminos and a splash of water to deglaze.",
      "In a second skillet, heat 2 tsp olive oil over medium-high. Add sliced cremini mushrooms and a pinch of salt. Sauté 6–7 min until they release water, then keep going until the water cooks off and they begin to brown.",
      "Add the rinsed spinach to the mushroom pan in batches — it wilts down dramatically in 1–2 min. Toss with tongs as it cooks. Once fully wilted, drain off any extra liquid (this removes some oxalate). Season with salt and pepper.",
      "Microwave or pan-steam broccoli until tender. Season lightly.",
      "Portion into 6 containers: rice base, beef mixture on top, broccoli alongside, mushroom-spinach mixture spooned across the beef. Add ¼ cup cold cottage cheese fresh when serving (not stored in container — texture suffers)."
    ],
    "notes": "Scaled to your usual 6-bowl batch. Adds ¼ cup cooked spinach + ½ cup cooked mushrooms per bowl. Spinach dialed back from a larger version — at ½ cup cooked vitamin K1 was hitting ~740% of RDA (safe but excessive); at ¼ cup it lands at ~370%, still very fixed with lower oxalate exposure. Potassium still closes its gap. Fresh baby spinach wilts down dramatically — 15 oz raw (three 5 oz clamshells) yields ~1.5 cups cooked. Draining off the wilted liquid removes some water-soluble oxalate. If you switch back to frozen at any point, 8 oz frozen chopped equals the same yield. Cremini chosen over white button for ergothioneine content and slightly lower selenium (keeps your stack under the UL ceiling). Egg-free per 2026 panel."
  },
  {
    "id": "std-yogurt-bowl",
    "group": "standard",
    "name": "Vanilla-Almond Protein Yogurt Bowl",
    "time": "3:30 PM",
    "servings": 1,
    "isMealPrep": false,
    "kcal": 452,
    "protein": 49,
    "carbs": 20,
    "fat": 22,
    "ingredients": [
      "1 cup Greek yogurt (2%)",
      "1 scoop vanilla whey protein powder",
      "1 tbsp almond butter",
      "½ oz raw almonds, roughly chopped",
      "¼ tsp ground cinnamon",
      "2 tbsp water or unsweetened almond milk (to loosen)",
      "Pinch of sea salt"
    ],
    "steps": [
      "Add yogurt to a bowl. Sift in protein powder.",
      "Add almond butter and cinnamon. Pour in liquid a splash at a time, stirring vigorously until smooth and mousse-like.",
      "Add salt and taste — the cinnamon and almond butter should give it a warm, almost cookie-dough character.",
      "Chop almonds and scatter on top right before eating (never mixed in ahead — they soften)."
    ],
    "notes": "Reworked to remove cocoa (moderately reactive on the 2026 panel). Almond butter carries the richness that the cocoa used to provide, cinnamon adds aromatic depth. Pre-mix the base up to 3 days ahead and store covered. Add almonds fresh."
  },
  {
    "id": "paleo-shake",
    "group": "paleo",
    "name": "Paleo Post-Workout Shake",
    "time": "6:45 AM",
    "servings": 1,
    "isMealPrep": false,
    "kcal": 464,
    "protein": 64,
    "carbs": 38,
    "fat": 7,
    "ingredients": [
      "2 scoops egg white protein powder",
      "1 tsp almond butter",
      "1 tsp chia seeds",
      "1 cup strawberries",
      "1 cup blueberries",
      "1 serving collagen peptides",
      "5 g creatine monohydrate",
      "8–10 oz water or unsweetened almond milk",
      "Ice (optional)"
    ],
    "steps": [
      "Add liquid to blender first.",
      "Add berries, then protein powder, collagen, chia, and almond butter.",
      "Add creatine and ice.",
      "Blend on high 45–60 seconds until smooth."
    ],
    "notes": "Egg white protein is the paleo swap for whey. Naked Egg or Now Sports are solid Sprouts options."
  },
  {
    "id": "paleo-sweet-potato-bowl",
    "group": "paleo",
    "name": "Beef, Egg & Sweet Potato Bowl",
    "time": "12:00 PM & 7:30 PM",
    "servings": 10,
    "isMealPrep": true,
    "kcal": 660,
    "protein": 44,
    "carbs": 46,
    "fat": 30,
    "ingredients": [
      "4 lb organic ground beef (85/15)",
      "10 whole eggs (1 per bowl)",
      "5 medium sweet potatoes (cubed, roasted)",
      "4 cups frozen broccoli florets",
      "2½ avocados (¼ avocado per bowl, sliced when serving)",
      "½ cup Kettle & Fire Beef Bone Broth (deglaze)",
      "2 tbsp olive oil",
      "2 tbsp garlic powder",
      "2 tsp onion powder",
      "2 tsp smoked paprika",
      "2 tsp cumin",
      "2 tsp salt",
      "1 tsp black pepper",
      "4 tbsp coconut aminos"
    ],
    "steps": [
      "Cube sweet potatoes (¾-inch dice). Toss with 1 tbsp olive oil, salt, pepper. Roast at 425°F for 30–35 min, flipping once.",
      "Brown the beef in a large skillet with 1 tbsp olive oil. Drain fat aggressively, then hot-water rinse in colander.",
      "Return beef to pan. Crack eggs in and scramble through. Add spices and coconut aminos. Deglaze with bone broth.",
      "Steam broccoli until tender.",
      "Portion into 10 containers: sweet potato base, beef on top, broccoli alongside. Slice fresh avocado at serving (never store cut avocado in container)."
    ],
    "notes": "Sweet potato beats white potato for nutrient density and slower-burning carbs. Bone-broth deglaze is non-negotiable for flavor."
  },
  {
    "id": "paleo-coconut-yogurt-bowl",
    "group": "paleo",
    "name": "Paleo Cocoa Coconut Yogurt Bowl",
    "time": "3:30 PM",
    "servings": 1,
    "isMealPrep": false,
    "kcal": 452,
    "protein": 33,
    "carbs": 23,
    "fat": 27,
    "ingredients": [
      "1 cup unsweetened coconut yogurt (Kite Hill or Cocoyo)",
      "1 scoop egg white protein powder",
      "1 tbsp unsweetened cocoa powder",
      "1 oz raw almonds, roughly chopped",
      "2 tbsp water or unsweetened almond milk",
      "Pinch of sea salt (important — amplifies chocolate)"
    ],
    "steps": [
      "Add coconut yogurt to a bowl. Add protein powder and cocoa.",
      "Pour in liquid a splash at a time to prevent clumping. Stir until smooth — texture is slightly looser than Greek yogurt.",
      "Add salt and taste. Coconut yogurt is mild, so the salt and cocoa do the heavy lifting.",
      "Chop almonds and scatter on top right before eating."
    ],
    "notes": "Coconut yogurt has far less protein than Greek (1g vs 17g/cup). The egg white protein scoop closes that gap. Add a second scoop if pushing protein higher."
  },
  {
    "id": "keto-shake",
    "group": "keto",
    "name": "Keto Morning Shake",
    "time": "6:45 AM",
    "servings": 1,
    "isMealPrep": false,
    "kcal": 591,
    "protein": 65,
    "carbs": 9,
    "fat": 29,
    "ingredients": [
      "2 scoops egg white protein powder",
      "1 tbsp almond butter",
      "1 tsp chia seeds",
      "½ cup strawberries (keto-friendly portion)",
      "1 tbsp MCT oil",
      "1 serving collagen peptides",
      "5 g creatine monohydrate",
      "8–10 oz water or unsweetened almond milk"
    ],
    "steps": [
      "Add liquid to blender.",
      "Add strawberries, protein powder, collagen, chia, almond butter, MCT oil.",
      "Add creatine, blend until smooth."
    ],
    "notes": "MCT oil is the engine here — fast-burning fuel that keeps you in ketosis. Start with 1 tsp if new to MCT, build up to 1 tbsp."
  },
  {
    "id": "keto-chicken-bowl",
    "group": "keto",
    "name": "Keto Chicken Thigh & Cauliflower Bowl",
    "time": "12:00 PM & 7:30 PM",
    "servings": 6,
    "isMealPrep": true,
    "kcal": 480,
    "protein": 47,
    "carbs": 4,
    "fat": 26,
    "ingredients": [
      "3 lb boneless skinless chicken thighs (~8 oz cooked per bowl)",
      "2 × 12 oz bags frozen cauliflower rice (or 1 fresh head, riced)",
      "2½ cups frozen broccoli florets",
      "2 tbsp olive oil (for cooking)",
      "6 tbsp extra virgin olive oil (1 tbsp drizzle per bowl)",
      "½ cup Kettle & Fire Beef Bone Broth (deglaze)",
      "1¼ tbsp garlic powder",
      "1¼ tsp onion powder",
      "1¼ tsp smoked paprika",
      "1¼ tsp cumin",
      "1¼ tsp salt",
      "½ tsp black pepper",
      "2½ tbsp coconut aminos"
    ],
    "steps": [
      "Pat chicken thighs dry. Season with salt, pepper, garlic powder, onion powder, paprika, cumin.",
      "Heat 2 tbsp olive oil in a large oven-safe skillet over medium-high. Sear thighs 3–4 min per side until golden.",
      "Transfer skillet to 400°F oven for 15–18 min until internal temp hits 165°F.",
      "Rest 5 min, then slice into bite-size pieces. Reserve pan juices.",
      "Sauté cauliflower rice in chicken pan with reserved juices and bone broth for 5–6 min. Add coconut aminos.",
      "Steam broccoli until tender.",
      "Portion into 6 containers: cauliflower rice base, sliced chicken on top, broccoli alongside. Drizzle 1 tbsp EVOO over each bowl when serving (replaces the fat you would have gotten from beef)."
    ],
    "notes": "The 1 tbsp olive oil drizzle is the key to keto macros with lean chicken thighs — easier on the gallbladder than the equivalent saturated fat from beef. Bone broth deglaze becomes critical since chicken has less natural flavor than beef."
  },
  {
    "id": "keto-snack",
    "group": "keto",
    "name": "Keto Snack — Eggs, Avocado & Almonds",
    "time": "3:30 PM",
    "servings": 1,
    "isMealPrep": false,
    "kcal": 495,
    "protein": 25,
    "carbs": 6,
    "fat": 40,
    "ingredients": [
      "3 hard boiled eggs",
      "½ avocado, sliced",
      "1 oz raw almonds",
      "Pinch of sea salt",
      "Squeeze of fresh lime juice"
    ],
    "steps": [
      "Boil eggs 9 minutes for fully set yolks. Ice bath, then peel.",
      "Halve and slice avocado. Squeeze lime over it to prevent browning and brighten the flavor.",
      "Plate eggs (halved or quartered), avocado, almonds. Salt to taste."
    ],
    "notes": "Batch boil 6 eggs at a time — keeps 5–7 days unpeeled in the fridge. Easy grab-and-go."
  },
  {
    "id": "shred-chicken-rice-powerbowl",
    "group": "general",
    "name": "Chicken & Rice Powerbowl",
    "time": "Lunch or dinner",
    "servings": 4,
    "isMealPrep": false,
    "kcal": 510,
    "protein": 45,
    "carbs": 29,
    "fat": 23,
    "ingredients": [
      "1.5 lb skin-on bone-in chicken thighs (skin removed after cooking)",
      "1 tsp olive oil",
      "1.5 tbsp garlic powder",
      "1 tbsp smoked paprika",
      "1 tbsp thyme or oregano",
      "¼ tsp cayenne pepper",
      "1 tbsp baking powder (crispy skin trick)",
      "Salt and black pepper",
      "½ cup Greek yogurt (sauce)",
      "2 tbsp mayonnaise (sauce)",
      "2 scallions (sauce)",
      "2 handfuls fresh cilantro (sauce)",
      "½ jalapeño, seeds removed (sauce)",
      "Juice of 1.5 limes (sauce)",
      "½ tsp chipotle powder (sauce)",
      "4 Persian cucumbers, thinly sliced (salad)",
      "3 tbsp red onion, finely diced (salad)",
      "2 tbsp cilantro, finely chopped (salad)",
      "1 tsp olive oil (salad)",
      "Juice of ½ small lemon (salad)",
      "1 box Kaizen low-carb rice (or regular rice / quinoa / cauliflower rice)",
      "1 avocado (2 slices per bowl)"
    ],
    "steps": [
      "Chicken: toss thighs with 1 tsp olive oil, salt, pepper, garlic powder, paprika, thyme/oregano, cayenne, and baking powder. Bake at 400°F for 40 min. Remove skin before plating.",
      "Sauce: process Greek yogurt, mayo, scallions, cilantro, jalapeño, lime juice, chipotle powder, and a pinch of salt until smooth. Taste and adjust.",
      "Salad: combine cucumbers, red onion, cilantro, olive oil, lemon juice, and a pinch of salt in a bowl. Mix and taste.",
      "Base: cook the Kaizen rice (or your chosen base) per package directions.",
      "Assemble: rice base → one chicken thigh → 2 spoonfuls of salad → 2 avocado slices → drizzle of sauce. Makes 4 servings."
    ],
    "notes": "Off-rotation — make this between meal-prep cycles when you want something fresh. Macros assume Kaizen low-carb rice. With jasmine rice instead, carbs jump to ~50g and protein drops by ~18g per serving. With cauliflower rice, carbs drop to ~13g (keto-friendly)."
  },
  {
    "id": "turkey-cabbage-bowl",
    "group": "general",
    "name": "Turkey & Cabbage Skillet Bowl",
    "time": "12:00 PM & 7:30 PM",
    "servings": 6,
    "isMealPrep": true,
    "kcal": 470,
    "protein": 49,
    "carbs": 18,
    "fat": 21,
    "ingredients": [
      "3 lb organic ground turkey (93/7)",
      "1 head red cabbage, chopped",
      "1 large white onion, diced",
      "8 oz cremini mushrooms, sliced",
      "0.82 cups cottage cheese (¼ cup per bowl, added fresh at serving)",
      "0.82 tbsp olive oil (for turkey)",
      "1.1 tsp olive oil (for mushroom + onion sauté)",
      "0.82 tbsp garlic powder",
      "⅔ tsp onion powder",
      "⅔ tsp smoked paprika",
      "⅔ tsp cumin",
      "⅔ tsp salt",
      "0.41 tsp black pepper",
      "1⅜ tbsp coconut aminos (wheat-free brand)"
    ],
    "steps": [
      "Heat 0.82 tbsp olive oil in your largest skillet or Dutch oven over medium-high. Brown the turkey, breaking it apart, 9–10 min until no pink remains. 93/7 needs only a light drain.",
      "Reduce heat. Add garlic powder, onion powder, paprika, cumin, salt, pepper. Stir, then add coconut aminos and a splash of water to deglaze.",
      "In a second pan, heat the remaining olive oil. Sauté mushrooms with a pinch of salt 6–7 min until their water cooks off; add the onion and cook 3–4 min until translucent.",
      "Add chopped cabbage to the turkey pot in batches — it wilts down dramatically. Cover between additions; 8–10 min total until tender with a little bite.",
      "Fold the mushroom-onion mixture through. Taste and adjust salt.",
      "Portion into 6 containers. Add ¼ cup cold cottage cheese fresh when serving (not stored in the container)."
    ],
    "notes": "Born from a happy accident — the scaled batch list was used with the FULL 3 lb of turkey, making this far more protein-dense than the beef bowl per calorie. Rice-free: bowl-level protein at two-thirds the calories (470 vs ~505 scaled beef bowl, with 10x less starch). Two of these + shake + whey scoop = ~1,715 kcal at 212g protein. Batch totals: ~2,810 kcal · P291 · C107 · F128."
  }
];
